# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: ad1297f76f431b6b74ed3307d9fb56df414cb21206a3577a227f1091d20f15ddc18cf96b8a6a30fc7176f9d2d8154b744f6a28bc64827a9de6fc60d6af376805

test:
  secret_key_base: b9a16d73f7fe818c79899fcd0cba3181087ece2d17c95ad3ee8542ac91fc3f55487c15ac1409380f2a02ff4bc1d2cc2bde229bae70892be4b6b891bc7b0cd20d

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
